# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build image
      if: success()
      run: docker build -t ${GITHUB_REPOSITORY}:${{ github.run_number }} .
    
    - name: Push to docker registry
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:${{ github.run_number }}
  
    - name: Deploy to Heroku
      if: success()
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Email that you use with heroku
        heroku_email: elhajjaji.anas@gmail.com
        # The appname to use for deploying/updating
        heroku_app_name: anas-learn-angular
        # Will deploy using Dockerfile in project root.
        usedocker: true
